### PR TITLE
next_step

### PR DESCRIPTION
**Pull request by marzieh67**
here is the next step of my weather app. adding js, CSS and api was the main changes. 

To-do:

- forecasting data
- correcting search item (does not work yet)
- adding more style
- city photo

### CODE REVIEW

**Comment by keponk** [comment]
Hey this is looking great! :) 

I have a question for you though. Would you accept the challenge of converting that main table into bootstrap items?

Pros & Cons:
* By using bootstrap "card decks" like we tried on the class yesterday, you automatically get the responsive behaviour when the screen size changes.
* Continuing with the tables, as the page gains more items and functionality you will notice is not so easy to "adapt". 
* On the other hand, learning to make tables behave the way you want manually might be a great learning on its own.
* Learning to use bootstrap can be a quick win when needed to use another different framework.

One last thing before I approve this PR is to create "issues" for each of those to-do items :) after that we can merge this.

**Comment by marzieh67** [comment]
> Hey this is looking great! :)
> 
> I have a question for you though. Would you accept the challenge of converting that main table into bootstrap items?
> 
> Pros & Cons:
> 
>     * By using bootstrap "card decks" like we tried on the class yesterday, you automatically get the responsive behaviour when the screen size changes.
> 
>     * Continuing with the tables, as the page gains more items and functionality you will notice is not so easy to "adapt".
> 
>     * On the other hand, learning to make tables behave the way you want manually might be a great learning on its own.
> 
>     * Learning to use bootstrap can be a quick win when needed to use another different framework.
> 
> 
> One last thing before I approve this PR is to create "issues" for each of those to-do items :) after that we can merge this.

Thanks a lot Joel. I will apply it :wink:

**Comment by golovnevs** [comment]
Hi, Marzieh! Could you please add me as a collaborator to your repo.

**Comment by golovnevs** [comment]
@keponk Hi, Joel! Can I approve this PR if you do not mind?

**Review by golovnevs — APPROVED** [review]

**Comment by golovnevs** [comment]
Feel free to merge  :)

**Pull request merged**
